global:
  imagePullPolicy: IfNotPresent
  otel:
    collectorEndpoint: http://otel-collector:4317
services:
  user:
    image: user-service
    tag: latest
  product:
    image: product-service
    tag: latest
  order:
    image: order-service
    tag: latest
  notification:
    image: notification-service
    tag: latest
frontend:
  image: shopease-frontend
  tag: latest

enabled:
  frontend: true
  product: true
  user: true
  order: true
  notification: true

autoscaling:
  enabled: false
  frontend:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 70
  product:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 70
  user:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 70
  order:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 70
  notification:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 70