{{- if .Values.global.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "umbrella.fullname" . }}-frontend
  annotations:
    kubernetes.io/ingress.class: {{ .Values.global.ingress.className | default "nginx" }}
spec:
  rules:
    {{- range .Values.global.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "umbrella.fullname" . }}-frontend
                port:
                  number: 80
    {{- end }}
{{- end }}
