{{- if .Values.db.createDevSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "db.secretName is required when db.createDevSecret=true" .Values.db.secretName }}
type: Opaque
data:
  {{- range $k, $v := .Values.db.dev }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
{{- end }}
