{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "order-service.fullname" . }}-migration
  labels:
    app.kubernetes.io/name: {{ include "order-service.name" . }}
    app.kubernetes.io/component: migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: {{ .Values.migration.ttlSecondsAfterFinished | default 300 }}
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: flyway-migrate
          image: "{{ .Values.migration.image }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.migration.imagePullPolicy }}
          
          env:
            - name: MIG_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ required "migration.secretName must be set (infra-owned)" .Values.migration.secretName | quote }}
                  key: ORDER_MIG_DB_USER
            - name: MIG_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ required "migration.secretName must be set (infra-owned)" .Values.migration.secretName | quote }}
                  key: ORDER_MIG_DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ required "migration.secretName must be set (infra-owned)" .Values.migration.secretName | quote }}
                  key: ORDER_DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ required "migration.secretName must be set (infra-owned)" .Values.migration.secretName | quote }}
                  key: ORDER_DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ required "migration.secretName must be set (infra-owned)" .Values.migration.secretName | quote }}
                  key: ORDER_DB_NAME
          args:
            - "-url=jdbc:sqlserver://$(DB_HOST):$(DB_PORT);databaseName=$(DB_NAME);encrypt=false;trustServerCertificate=true"
            - "-user=$(MIG_DB_USER)"
            - "-password=$(MIG_DB_PASSWORD)"
            - "-schemas=$(DB_NAME)"
            - "-defaultSchema=$(DB_NAME)"
            - "-baselineOnMigrate=true"
            - "-baselineVersion=1"
            - "migrate"
{{- end }}
