{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "order-service.fullname" . }}-migration
  labels:
    app.kubernetes.io/name: {{ include "order-service.name" . }}
    app.kubernetes.io/component: migration
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: flyway-migrate
          image: "{{ .Values.migration.image }}{{ if .Values.migration.tag }}:{{ .Values.migration.tag }}{{ end }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.migration.imagePullPolicy }}
          env:
            - name: MIG_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-migration" .Chart.Name) .Values.migration.secretName | quote }}
                  key: MIG_DB_USER
            - name: MIG_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-migration" .Chart.Name) .Values.migration.secretName | quote }}
                  key: MIG_DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-migration" .Chart.Name) .Values.migration.secretName | quote }}
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-migration" .Chart.Name) .Values.migration.secretName | quote }}
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-migration" .Chart.Name) .Values.migration.secretName | quote }}
                  key: DB_NAME
          args:
            - >
              -url=jdbc:sqlserver://$(DB_HOST):$(DB_PORT);databaseName=$(DB_NAME)
              -user=$(MIG_DB_USER)
              -password=$(MIG_DB_PASSWORD)
              migrate
{{- end }}
