{{- if .Values.credentials.createDevSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "credentials.secretName is required when credentials.createDevSecret=true" .Values.credentials.secretName }}
type: Opaque
data:
  {{- range $k, $v := .Values.credentials.dev }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
{{- end }}
